# Generated by Django 5.2.4 on 2025-07-03 02:33

import django.db.models.deletion
from django.db import migrations, models


def create_default_client_site(apps, schema_editor):
    Client = apps.get_model('app_clients', 'Client')
    Site = apps.get_model('app_clients', 'Site')

    client, _ = Client.objects.get_or_create(
        nom='Client par défaut',
        defaults={
            'telephone': '0000000000',
            'email': 'default@mif.com',
            'adresse': 'Adresse par défaut'
        }
    )

    Site.objects.get_or_create(
        id=1,
        defaults={
            'nom': 'Site par défaut',
            'adresse': 'Adresse du site par défaut',
            'client': client
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du site')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='app_clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.RunPython(create_default_client_site),
    ]
