# Generated by Django 5.2.4 on 2025-07-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_techniciens', '0002_create_default_technicien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicien',
            options={'verbose_name': 'Technicien', 'verbose_name_plural': 'Techniciens'},
        ),
        migrations.AlterField(
            model_name='technicien',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='specialite',
            field=models.CharField(max_length=100, verbose_name='Spécialité'),
        ),
    ]
