# Generated by Django 5.2.4 on 2025-07-03 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interventions', '0002_alter_intervention_options_intervention_date_and_more'),
        ('app_rapports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapport',
            options={'verbose_name': 'Rapport', 'verbose_name_plural': 'Rapports'},
        ),
        migrations.AlterField(
            model_name='rapport',
            name='contenu',
            field=models.TextField(verbose_name='Contenu du rapport'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='rapports/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='intervention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='app_interventions.intervention', verbose_name='Intervention'),
        ),
    ]
