# Generated by Django 5.2.4 on 2025-07-03 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0003_alter_client_options_client_email_client_telephone_and_more'),
        ('app_materiels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiel',
            options={'verbose_name': 'Matériel', 'verbose_name_plural': 'Matériels'},
        ),
        migrations.AddField(
            model_name='materiel',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='app_clients.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='date_installation',
            field=models.DateField(verbose_name="Date d'installation"),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='marque',
            field=models.CharField(max_length=100, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom du matériel'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='reference',
            field=models.CharField(max_length=100, verbose_name='Référence'),
        ),
    ]
