# Generated by Django 5.2.4 on 2025-07-03 02:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0003_alter_client_options_client_email_client_telephone_and_more'),
        ('app_interventions', '0001_initial'),
        ('app_materiels', '0002_alter_materiel_options_materiel_site_and_more'),
        ('app_techniciens', '0003_alter_technicien_options_alter_technicien_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'verbose_name': 'Intervention', 'verbose_name_plural': 'Interventions'},
        ),
        migrations.AddField(
            model_name='intervention',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'intervention"),
        ),
        migrations.AddField(
            model_name='intervention',
            name='signature_path',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_clients.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app_clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_cloture',
            field=models.DateField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app_materiels.materiel', verbose_name='Matériel'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technicien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app_techniciens.technicien', verbose_name='Technicien'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_interventions.intervention', verbose_name='Intervention')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='app_interventions.intervention', verbose_name='Intervention')),
            ],
        ),
        migrations.CreateModel(
            name='FichierJoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='fichiers_joints/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_joints', to='app_interventions.intervention', verbose_name='Intervention')),
            ],
        ),
    ]
